### ISSUE TITLE
Update scalalogging

### ISSUE THREAD

**Issue by francisdb** [danielkorzekwa/bayes-scala#14]
Since `scalalogging` is not further developed (last commit 7 months ago) and is not available for scala 2.11.x I suggest you drop it and migrate to plain slf4j

**Comment by danielkorzekwa** [comment]
are you sure, I can see scala logging for 2.11:
http://mvnrepository.com/artifact/com.typesafe.scala-logging

**Comment by francisdb** [comment]
I see, the sbt/pom file is probably pointing to the old version with the different artifact id. We should update to the new one.

**Comment by danielkorzekwa** [comment]
sure, let's do it.

On 26 February 2015 at 18:19, Francis De Brabandere <
notifications@github.com> wrote:

> I see, the sbt/pom file is probably pointing to the old version with the
> different artifact id. We should update to the new one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielkorzekwa/bayes-scala/issues/14#issuecomment-76221774>
> .
>



-- 
Daniel Korzekwa
Machine Learning Engineer
priv: https://www.linkedin.com/in/danielkorzekwa <http://danmachine.com/>
blog: http://blog.danmachine.com
