### ISSUE TITLE
deploy bayes-scala for Scala 2.11 to snapshot maven repo

### ISSUE THREAD

**Issue by francisdb** [danielkorzekwa/bayes-scala#20]
Continuation of #12
We are on scala 2.11 and the cross-build is already set up so I suppose this would not be too hard?

**Comment by danielkorzekwa** [comment]
DONE. 
bayes-scala for both 2.10 and 2.11 is deployed to sonatype now.

test it please.

some resources for sbt + travis + cross build:
http://rosslawley.co.uk/posts/how-to-handle-multiple-scala-versions/
http://www.onegeek.com.au/scala/setting-up-travis-ci-for-scala
http://www.javacodegeeks.com/2014/10/testing-your-plugin-with-multiple-version-of-play.html
http://www.scala-sbt.org/0.13/docs/Howto-Scala.html

**Comment by francisdb** [comment]
`[SUCCESSFUL ] com.github.danielkorzekwa#bayes-scala_2.11;0.5-SNAPSHOT!bayes-scala_2.11.jar (1399ms)`

:+1:
