### ISSUE TITLE
Replace ejml with breeze

### ISSUE THREAD

**Issue by danielkorzekwa** [danielkorzekwa/bayes-scala#24]
Why?
- Simplify the code, use single matrix library instead of two.
- Breeze with native extenstions seems to be faster than ejml.
- Breeze is a Scala lib, EJML is a Java lib.
- Promote breeze, it's a nice lib.

**Comment by nightscape** [comment]
:+1:
I was checking the [performance comparisons for Netlib](https://github.com/fommil/matrix-toolkits-java#performance-to-other-libraries) (which breeze-native uses under the hood) a few days ago, and it seems the only performance advantage of ejml is for small matrices.
