### ISSUE TITLE
Unsetting the value on a Categorical

### ISSUE THREAD

**Issue by francisdb** [danielkorzekwa/bayes-scala#27]
Currently the setValue takes an `int` and wraps it in a `Some` so there is no way to go back to `None`

**Comment by danielkorzekwa** [comment]
Done.

sat.clearValue()
assertVector(Array(0.3620, 0.2884, 0.3496), infer(grade).cpd, 0.0001)

**Comment by francisdb** [comment]
:+1:

**Comment by francisdb** [comment]
The readme still needs an update

**Comment by francisdb** [comment]
Looking good!
