### ISSUE TITLE
Non-snapshot release to maven central

### ISSUE THREAD

**Issue by francisdb** [danielkorzekwa/bayes-scala#28]
As we actually plan to start using bayes-scala in production we would like to see a fixed release.

**Comment by danielkorzekwa** [comment]
ok, will do it by the end of the next week, as well as #27.

Version to be released: 0.5

**Comment by francisdb** [comment]
Thanks!

**Comment by danielkorzekwa** [comment]
The release of bayes-scala v0.5 has been just promoted on nexus, waiting now for the Sonatype team to activate the sync process.

**Comment by francisdb** [comment]
Sync is working:
http://search.maven.org/#search%7Cga%7C1%7Cbayes-scala
