### ISSUE TITLE
remove breeze-natives

### ISSUE THREAD

**Issue by danielkorzekwa** [danielkorzekwa/bayes-scala#34]
netlib speeds up breeze for big md and mm operations only.

**Comment by francisdb** [comment]
@danielkorzekwa time for an other release?

**Comment by danielkorzekwa** [comment]
If you can't live without it I will do it.

**Comment by francisdb** [comment]
well, not that I would die without it, just would be nice to have a bit more frequent releases.

**Comment by danielkorzekwa** [comment]
I should create it within a month or so, first planning to update docs and make some refactoring changes to factor graph impl.

**Comment by francisdb** [comment]
ok, great
