### ISSUE TITLE
Publish bayes-scala on the Maven central repository

### ISSUE THREAD

**Issue by erikkaplun** [danielkorzekwa/bayes-scala#4]
Currently the only way of adding bayes-scala as a dependency is copying the source or a compiler .jar to a project's `lib` directory, am I correct? But it would be really nice if you could just add it to `libraryDependencies` or a Maven build configuration file.

**Comment by francisdb** [comment]
FYI https://github.com/danielkorzekwa/bayes-scala/issues/12
